### ISSUE TITLE
 Робота над помилками.

### ISSUE THREAD

**Issue by Alecto** [Kateryna-programmer/simple-landing#1]
1)

У CSS / HTML / JS не прийнято використання _ для іменування класів / ідентифікаторів / змінних.
Відповідно до концепції БЕМ складові слова поділяються одним тире.
Підкреслення, як стиль іменування, використовується в таких змінних мов як PHP, PY.
Використовуйте методологію БЕМ, яка була розібрана в класі + є опис у презентації + окремий урок з посиланням на документацію з розбором можливих помилок.
Довідник https://ru.bem.info/methodology/quick-start/

![image](https://github.com/Kateryna-programmer/simple-landing/assets/8464662/dd861e92-63d3-4600-85e4-c5a6f4874c90)

2)
именование классов плохо продумано
![image](https://github.com/Kateryna-programmer/simple-landing/assets/8464662/d8348648-8c48-4b41-a8c2-84584c968ca7)

**Comment by Kateryna-programmer** [comment]
Не розумію, що саме не так в назвах класів у футері? Спочатку назва footer - це блок, далі через __ йде елемент - для списку - list, для пунктів списку - item, для посилань - link - це з уроку,як ви говорили... Чому погане найменування, якщо в хедері у мене такі самі класи?

**Comment by Alecto** [comment]
footer__link э елементом item, а не footer

чт, 17 серп. 2023 р. о 17:33 Kateryna Kostewa ***@***.***>
пише:

**Comment by Kateryna-programmer** [comment]
Андрій, вибачте, але я нічого не зрозуміла з вашого повідомлення
"footer__link э елементом item, а не footer"  зовсім не зрозуміла, що
таке "... а не footer?" футер - це в мене назва блоку, не бачу проблеми

Чому "лінк є елементом ітем"? Ви маєте на увазі, що до посилання треба клас
footer-item?? це ж посилання, логічно дати йому клас footer__link? чи я не
права?

от ваш код, у нього клас footer__links, чому мій клас footer__link не
підходить??

<a class="footer__links" href="https://www.linkedin.com/in/andrii-fomenko/"
target="_blank">
          <i class="fab fa-linkedin"></i>
        </a>

чт, 17 авг. 2023 г. в 18:50, Andrii Fomenko ***@***.***>:

**Comment by Alecto** [comment]
чт, 17 серп. 2023, 21:54 користувач Kateryna Kostewa <
***@***.***> пише:

> Андрій, вибачте, але я нічого не зрозуміла з вашого повідомлення
> "footer__link э елементом item,

Мав на увазі ваш клас, ліниво було писати його повністю


а не footer" зовсім не зрозуміла, що
> таке "... а не footer?" футер - це в мене назва блоку, не бачу проблеми

Саме так


>
> Чому "лінк є елементом ітем"? Ви маєте на увазі, що до посилання треба
> клас
> footer-item?? це ж посилання, логічно дати йому клас footer__link? чи я не
> права?

Можливо і так. Але ваша поточна реалізація мені не зрозуміла.



>
> от ваш код, у нього клас footer__links, чому мій клас footer__link не
> підходить??

Тому що в мене лінк - елемента футера, айтемів в мене немає. Лінк і є
айтем.
У вас щось мені незрозуміле.

**Comment by Kateryna-programmer** [comment]
Виправила бем та класи у футері
https://github.com/Kateryna-programmer/simple-landing
https://kateryna-programmer.github.io/simple-landing/

пт, 18 авг. 2023 г. в 08:42, Andrii Fomenko ***@***.***>:

**Comment by Alecto** [comment]
хорошо, принято
